CREATE TABLE execution_stats
(
  tpch_scaling_factor numeric,
  k integer,
  strategy_name text,
  query_id text,
  attributes text[],
  original_histograms numeric[],
  transformed_histograms_values numeric[],
  query_attributes_values numeric[],
  query_template text,
  all_queries text[],
  function_description text,
  executed_queries_count integer,
  executed_queries_results_sizes integer[],
  executed_queries_function_values numeric[],
  executed_queries_query_plans text[],
  executed_queries_start timestamp without time zone[],
  executed_queries_end timestamp without time zone[],
  executed_queries_seconds integer[],
  algorithm_start timestamp without time zone,
  algorithm_end timestamp without time zone,
  algorithm_seconds integer,
  final_query text,
  final_query_execution_start timestamp without time zone,
  final_query_execution_end timestamp without time zone,
  final_query_execution_seconds integer,
  traditional_topk_query text,
  traditional_topk_query_template text,
  traditional_topk_query_execution_start timestamp without time zone,
  traditional_topk_query_execution_end timestamp without time zone,
  traditional_topk_query_execution_seconds integer,
  execution_log text
)
